from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
import json
import os


def create_session_report(session_data: dict, output_path: str = None):
    """Generate a Word document report from session data."""
    doc = Document()

    session_id = session_data.get("session_id", "unknown")
    data = session_data.get("data", {})

    # Title
    title = doc.add_heading(f'EchoSensei — Clinical Report', 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Session Info
    p = doc.add_paragraph()
    run = p.add_run('Session ID: ')
    run.bold = True
    p.add_run(session_id)

    p2 = doc.add_paragraph()
    run2 = p2.add_run('Domain: ')
    run2.bold = True
    p2.add_run('Healthcare')

    p3 = doc.add_paragraph()
    run3 = p3.add_run('Created: ')
    run3.bold = True
    p3.add_run(session_data.get("created_at", "Unknown"))

    p4 = doc.add_paragraph()
    run4 = p4.add_run('Language: ')
    run4.bold = True
    p4.add_run(session_data.get("language", "Unknown"))

    p5 = doc.add_paragraph()
    run5 = p5.add_run('Total Turns: ')
    run5.bold = True
    p5.add_run(str(session_data.get("turn", 0)))

    doc.add_paragraph('')

    # Extracted Data
    doc.add_heading('Extracted Data', level=1)

    if data:
        for key, value in data.items():
            if value and value not in ("", "null", "unknown", 0, None):
                p = doc.add_paragraph()
                run = p.add_run(f'{key.replace("_", " ").title()}: ')
                run.bold = True
                run.font.size = Pt(11)
                p.add_run(str(value))
    else:
        doc.add_paragraph('No data extracted in this session.')

    # History
    history = session_data.get("history", [])
    if history:
        doc.add_heading('Conversation History', level=1)
        for turn in history:
            turn_num = turn.get("turn", "?")
            timestamp = turn.get("timestamp", "")
            new_data = turn.get("new_data", {})
            if new_data:
                items = [f"{k}: {v}" for k, v in new_data.items() if v and v not in ("", 0, None)]
                if items:
                    doc.add_paragraph(f'Turn {turn_num} ({timestamp})', style='List Bullet')
                    for item in items:
                        doc.add_paragraph(f'  • {item}', style='List Bullet 2')

    # Footer
    doc.add_paragraph('\n')
    footer = doc.add_paragraph('Generated by EchoSensei — AI Conversational Intelligence Platform')
    footer.alignment = WD_ALIGN_PARAGRAPH.RIGHT

    # Save
    if not output_path:
        output_path = f"EchoSensei_{session_id}_Clinical_Report.docx"
    doc.save(output_path)
    print(f"✅ Report saved as {output_path}")
    return output_path


def create_migration_guide():
    doc = Document()

    title = doc.add_heading('EchoSensei: Migration & Handoff Guide', 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    p = doc.add_paragraph()
    run = p.add_run('Conversation ID (Antigravity): ')
    run.bold = True
    p.add_run('63039053-dd38-4e58-837a-a2e9759f0e94')
    
    doc.add_heading('1. UI & Visual Identity', level=1)
    doc.add_paragraph(
        'The interface follows a "Vibrant Cyber-Clinical" aesthetic with heavy animations. '
        'Key design tokens include:'
    )
    list_items = [
        'Main UI: Colorful drifting orbs + particle field over deep dark indigo (#060815).',
        'Loading Page: Pure Black (#000000) with canvas-based EKG heartbeat + boot sequence.',
        'Layout: Top Navbar with 5 tabs (Dashboard, Sensei AI, History, Analytics, About).',
        'Typography: Outfit (Headers) and Inter (Body) for premium legibility.',
        'Domain switching: Healthcare / Finance / Survey / General with animated chips.',
        'Text + Voice input: Dual input modes on dashboard and chat pages.',
        'Editable Review: Click Edit to modify extracted entities inline.',
        'Session History: Searchable past sessions with domain badges and time-ago labels.',
        'Analytics: Donut chart (domains) + Bar chart (languages) + reasoning timeline.'
    ]
    for item in list_items:
        doc.add_paragraph(item, style='List Bullet')

    doc.add_heading('2. Core System Features', level=1)
    feat_items = [
        'Multilingual ASR: IndicConformer / Whisper fallback (Hindi, Tamil, Kannada, English, code-mixed).',
        'Multi-Domain LLM: Dynamic prompt templates for Healthcare, Finance, Survey, General.',
        'Editable Review Interface: Human validation & correction of extracted data.',
        'Session Management: Create, list, search, delete sessions with full history.',
        'Longitudinal Dashboard: Analytics across all sessions with charts.',
        'Text + Voice Input: Dual-mode input on dashboard and chat pages.',
        'TTS: Web Speech API for Sensei voice responses.',
        'PDF Export: Domain-aware report generation.'
    ]
    for item in feat_items:
        doc.add_paragraph(item, style='List Bullet')

    doc.add_heading('3. Migration Instructions', level=1)
    
    doc.add_heading('Step 1: Code Migration', level=2)
    doc.add_paragraph('Copy the entire echosensei directory to your new workspace.')

    doc.add_heading('Step 2: Environment Setup', level=2)
    doc.add_paragraph('Install dependencies:')
    p2 = doc.add_paragraph()
    run2 = p2.add_run('pip install -r requirements.txt')
    run2.font.name = 'Courier New'
    run2.font.size = Pt(10)

    doc.add_heading('Step 3: Set GROQ_API_KEY', level=2)
    doc.add_paragraph('Set your Groq API key as an environment variable:')
    p3 = doc.add_paragraph()
    run3 = p3.add_run('set GROQ_API_KEY=your_key_here')
    run3.font.name = 'Courier New'
    run3.font.size = Pt(10)

    doc.add_heading('Step 4: Run', level=2)
    doc.add_paragraph('python server.py')
    doc.add_paragraph('Then open http://localhost:5000')

    footer = doc.add_paragraph('Generated by EchoSensei AI — Conversational Intelligence Platform.')
    footer.alignment = WD_ALIGN_PARAGRAPH.RIGHT

    path = "EchoSensei_Migration_Guide.docx"
    doc.save(path)
    print(f"✅ Migration guide saved as {path}")


if __name__ == '__main__':
    create_migration_guide()
